---
- name: Fail if sap_vm_provision_kubevirt_vm_os_user_password is not set and sap_vm_provision_kubevirt_vm_guest_ssh_auth_mechanism is set to password
  ansible.builtin.fail:
    msg: Password is not allowed to be empty or undefined (sap_vm_provision_kubevirt_vm_os_user_password).
  when:
    - sap_vm_provision_kubevirt_vm_guest_ssh_auth_mechanism == "password"
    - sap_vm_provision_kubevirt_vm_os_user_password == "" or sap_vm_provision_kubevirt_vm_os_user_password == null

- name: Ansible Task block for looped provisioning of KubeVirt Virtual Machines
  any_errors_fatal: true
  # Using environment, no_log is ineffective and log will show 'EXEC /bin/sh -c 'ENV_VAR=value python3 /AnsiballZ_ansible_module_name.py && sleep 0'
  # Therefore do not use environment for secrets, use only for non-sensitive values as this will reduce Ansible Task parameters.
  # environment:
  block:

    - name: Set fact to hold loop variables from include_tasks
      ansible.builtin.set_fact:
        register_provisioned_host_all: []

    - name: Provision hosts to KubeVirt
      register: __sap_vm_provision_task_provision_host_all_run
      ansible.builtin.include_tasks:
        file: "{{ 'platform_' + sap_vm_provision_iac_type }}/{{ sap_vm_provision_iac_platform }}/execute_provision.yml"

    - name: Add hosts provisioned to the Ansible Inventory
      register: __sap_vm_provision_task_provision_host_all_add
      ansible.builtin.add_host:
        name: "{{ add_item[0].host_node }}"
        groups: "{{ add_item[0].sap_system_type + '_' if (add_item[0].sap_system_type != '') }}{{ add_item[0].sap_host_type }}"
        ansible_host: "{{ add_item[0].provisioned_private_ip }}"
        ansible_user: "{{ sap_vm_provision_kubevirt_vm_os_user }}"
      loop: "{{ ansible_play_hosts | map('extract', hostvars, 'register_provisioned_host_all') }}"
      loop_control:
        label: "{{ add_item[0].host_node }}"
        loop_var: add_item

# Cannot override any variables from extravars input, see https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_variables.html#understanding-variable-precedence
# Ensure no default value exists for any prompted variable before execution of Ansible Playbook

    - name: Set fact to hold all inventory hosts in all groups
      ansible.builtin.set_fact:
        groups_merged_list: "{{ [ [ groups['hana_primary'] | default([]) ] , [ groups['hana_secondary'] | default([]) ] , [ groups['nwas_ascs'] | default([]) ] , [ groups['nwas_ers'] | default([]) ] , [ groups['nwas_pas'] | default([]) ] , [ groups['nwas_aas'] | default([]) ] ] | flatten | select() }}"

    - name: Set Ansible Vars
      register: __sap_vm_provision_task_ansible_vars_set
      ansible.builtin.include_tasks:
        file: common/set_ansible_vars.yml

  rescue:
    # This requires no_log set on each Ansible Task, and not set on the Ansible Task Block
    # This requires an Ansible Task Block containing the Ansible Tasks for calling
    # Infrastructure Platform APIs (via Ansible Modules)
    - name: Show errors in task outputs
      ansible.builtin.fail:
        msg: "{{ lookup('ansible.builtin.vars', loop_item) }}"
      loop:
        - __sap_vm_provision_task_provision_host_all_run
        - __sap_vm_provision_task_provision_host_single
        - __sap_vm_provision_task_provision_host_single_info
        - __sap_vm_provision_task_ansible_facts_host_disks_info
        - __sap_vm_provision_task_provision_host_all_add
      loop_control:
        loop_var: loop_item
        index_var: loop_item_index
        label: "{{ 'Variable No. ' + (loop_item_index | string) }}"
      when:
        - lookup('ansible.builtin.vars', loop_item, default='') | length > 0
        - not lookup('ansible.builtin.vars', loop_item, default='') is skipped
        - lookup('ansible.builtin.vars', loop_item, default='') is failed

- name: Write private ssh key to ansible_controller
  delegate_to: "{{ sap_vm_provision_kubevirt_vm_ansible_controller }}"
  no_log: true
  ansible.builtin.copy:
    dest: "{{ sap_vm_provision_ssh_host_private_key_file_path }}"
    content: "{{ sap_vm_provision_ssh_host_private_key_data }}"
    mode: "0600"
  when: sap_vm_provision_kubevirt_vm_guest_ssh_auth_mechanism == "private_key_data"

- name: Ansible Task block to execute on target inventory hosts
  remote_user: "{{ sap_vm_provision_kubevirt_vm_os_user }}"
  become: true
  become_user: root
  delegate_to: "{{ inventory_hostname }}"
  vars:
    ansible_password: "{{ sap_vm_provision_kubevirt_vm_os_user_password }}"
    ansible_ssh_private_key_file: "{{ sap_vm_provision_ssh_host_private_key_file_path }}"
    ansible_ssh_common_args: "-o ConnectTimeout=180 -o ControlMaster=auto -o ControlPersist=3600s -o UserKnownHostsFile=/dev/null -o ForwardX11=no -o ProxyJump={{ __sap_vm_provision_kubevirt_vm_register_execution_host_user }}@{{ sap_vm_provision_execution_host }}"

  block:

    # Required to collect the remote host's facts for further processing
    # in the following steps
    - name: Gather host facts
      ansible.builtin.setup:

    # Must be set to short hostname,
    # so that command 'hostname' and 'hostname -s' return the short hostname only;
    # otherwise may cause error with SAP SWPM using name.domain.com.domain.com
    - name: Change system hostname (must be set to short name and not FQDN, as required by SAP)
      ansible.builtin.hostname:
        name: "{{ inventory_hostname_short }}"

    - name: Set /etc/hosts
      register: __sap_vm_provision_task_os_etc_hosts
      ansible.builtin.include_tasks:
        file: common/set_etc_hosts.yml

    - name: Set /etc/hosts for HA
      register: __sap_vm_provision_task_os_etc_hosts_ha
      ansible.builtin.include_tasks:
        file: common/set_etc_hosts_ha.yml
      when:
        - (groups["hana_secondary"] is defined and (groups["hana_secondary"] | length>0)) or (groups["nwas_ers"] is defined and (groups["nwas_ers"] | length>0)) or (groups["anydb_secondary"] is defined and (groups["anydb_secondary"] | length>0))

    - name: Set /etc/hosts for Scale-Out
      register: __sap_vm_provision_task_os_etc_hosts_scaleout
      ansible.builtin.include_tasks:
        file: common/set_etc_hosts_scaleout.yml
      when:
        - (groups["hana_primary"] is defined and (groups["hana_primary"] | length>0)) and (sap_vm_provision_calculate_sap_hana_scaleout_active_coordinator is defined or sap_vm_provision_calculate_sap_hana_scaleout_active_worker is defined or sap_vm_provision_calculate_sap_hana_scaleout_standby is defined)

    - name: Set vars for sap_storage_setup Ansible Role
      register: __sap_vm_provision_task_ansible_vars_storage
      ansible.builtin.include_tasks:
        file: common/set_ansible_vars_storage.yml

    - name: Register Web Forward Proxy
      ansible.builtin.include_tasks:
        file: common/register_proxy.yml

    - name: Register Package Repositories
      ansible.builtin.include_tasks:
        file: common/register_os.yml

  always:

    - name: Delete private ssh key from ansible_controller
      delegate_to: "{{ sap_vm_provision_register_ansible_controller }}"
      become: false
      ansible.builtin.file:
        path: "{{ sap_vm_provision_ssh_host_private_key_file_path }}"
        state: absent
      when: sap_vm_provision_kubevirt_vm_guest_ssh_auth_mechanism == "private_key_data"
