# SPDX-License-Identifier: Apache-2.0
---

- name: SAP VM Provision - Post Deployment notification
  ansible.builtin.debug:
    msg: "There are no Post Deployment tasks for SAP on this Infrastructure Platform"
