---
- name: Create the nmstate operator namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        labels:
          kubernetes.io/metadata.name: openshift-nmstate
          name: openshift-nmstate
        name: openshift-nmstate
      spec:
        finalizers:
          - kubernetes

- name: Create the OperatorGroup
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: operators.coreos.com/v1
      kind: OperatorGroup
      metadata:
        annotations:
          olm.providedAPIs: NMState.v1.nmstate.io
        generateName: openshift-nmstate-
        name: openshift-nmstate-tn6k8
        namespace: openshift-nmstate
      spec:
        targetNamespaces:
          - openshift-nmstate

- name: Wait for nmstate OperatorGroup to be created
  kubernetes.core.k8s_info:
    api_version: operators.coreos.com/v1
    kind: OperatorGroup
    name: openshift-nmstate-tn6k8
    namespace: openshift-nmstate
  register: operatorgroup_status
  retries: 30
  delay: 10
  until: operatorgroup_status.resources | default([]) | length > 0

- name: Subscribe to the nmstate Operator
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        labels:
          operators.coreos.com/kubernetes-nmstate-operator.openshift-nmstate: ""
        name: kubernetes-nmstate-operator
        namespace: openshift-nmstate
      spec:
        channel: stable
        installPlanApproval: Automatic
        name: kubernetes-nmstate-operator
        source: redhat-operators
        sourceNamespace: openshift-marketplace

- name: Wait for Subscription to have an InstallPlan
  kubernetes.core.k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    name: kubernetes-nmstate-operator
    namespace: openshift-nmstate
  register: subscription_status
  retries: 30
  delay: 10
  until: subscription_status.resources[0].status.installplan.name is defined

- name: Wait for InstallPlan to complete
  kubernetes.core.k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: InstallPlan
    name: "{{ subscription_status.resources[0].status.installplan.name }}"
    namespace: openshift-nmstate
  register: installplan_status
  retries: 30
  delay: 10
  until: installplan_status.resources[0].status.phase == "Complete"

- name: Create instance of the nmstate operator
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: nmstate.io/v1
      kind: NMState
      metadata:
        name: nmstate

- name: Wait for NMState instance to be created
  kubernetes.core.k8s_info:
    api_version: nmstate.io/v1
    kind: NMState
    name: nmstate
  register: nmstate_status
  retries: 30
  delay: 10
  until: nmstate_status.resources | default([]) | length > 0

- name: Wait and check for pod with label name nmstate-webhook under the namespace "{{ sap_hypervisor_node_preconfigure_nmstate_namespace }}"
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: "{{ sap_hypervisor_node_preconfigure_nmstate_namespace }}"
    label_selectors:
      - name=nmstate-webhook
  register: sap_hypervisor_node_preconfigure_register_webhook_pod
  retries: 5
  delay: 60
  until: sap_hypervisor_node_preconfigure_register_webhook_pod.resources | selectattr('status.phase', 'equalto', 'Running') | list | length == sap_hypervisor_node_preconfigure_register_webhook_pod.resources | length

- name: Check if nmstate webhook endpoint is available
  include_tasks: wait_for_webhook_endpoints.yml
  vars:
    webhook_service_name: nmstate-webhook
    webhook_namespace: openshift-nmstate
