# SPDX-License-Identifier: Apache-2.0
---
# Internal role variables

# Host dictionary name for simplified lookups.
__sap_vm_provision_host_spec_dict_name:
  "{{ 'sap_vm_provision_' ~ sap_vm_provision_iac_platform ~ '_host_specifications_dictionary' }}"

__sap_vm_provision_host_image_dict_name:
  "{{ 'sap_vm_provision_' ~ sap_vm_provision_iac_platform ~ '_host_os_image_dictionary' }}"

# Plan dictionary for simplified lookups.
__sap_vm_provision_host_dict_plan:
  "{{ lookup('ansible.builtin.vars', __sap_vm_provision_host_spec_dict_name)[sap_vm_provision_host_specification_plan] }}"

# Hostname specification dictionary for simplified lookups, with optional Scaleout.
__sap_vm_provision_host_dict_spec:
  "{{ __sap_vm_provision_host_dict_plan[__sap_vm_provision_fact_scaleout_origin_hostname | d(inventory_hostname)] }}"

# Path to platform task file.
__sap_vm_provision_task_file:
  "{{ 'platform_' + sap_vm_provision_iac_type }}/{{ sap_vm_provision_iac_platform }}"

# Letters for calculating storage volume device names. max 25 volumes.
__sap_vm_provision_storage_vol_letters: "bcdefghijklmnopqrstuvwxyz"

# List of provisioning results for all hosts combined into one list.
__sap_vm_provision_fact_provisioned_hosts: []


# IBM PowerVS specific variables
# IBM Power VS location to the colocated IBM Cloud Availability Zone (VPC)
__sap_vm_provision_ibmcloud_powervs_location_to_ibmcloud_availability_zone:
  dal10: "us-south-1"
  dal12: "us-south-2"
  us-south: "us-south-3" # naming of IBM Power VS location 'us-south' was previous naming convention, would otherwise be 'dal13'
  us-east: "us-east-1" # naming of IBM Power VS location 'us-east' was previous naming convention, would otherwise be 'wdc04'
  wdc06: "us-east-2"
  wdc07: "us-east-3"
  sao01: "br-sao-1"
  sao02: "br-sao-2"
  tor01: "ca-tor-1"
  eu-de-1: "eu-de-2" # naming of IBM Power VS location 'eu-de-1' was previous naming convention, would otherwise be 'fra04'
  eu-de-2: "eu-de-3" # naming of IBM Power VS location 'eu-de-2' was previous naming convention, would otherwise be 'fra05'
  lon04: "eu-gb-1"
  lon06: "eu-gb-3"
  mad02: "eu-es-1"
  mad04: "eu-es-2"
  syd04: "au-syd-2"
  syd05: "au-syd-3"
  tok04: "jp-tok-2"
  osa21: "jp-osa-1"

# IBM Power VS location to the IBM Power VS Region API Endpoints
# IBM Cloud Regional API Endpoint = https://<<sap_vm_provision_ibmcloud_region>>.cloud.ibm.com/
# IBM Power VS (on IBM Cloud) Regional API Endpoint = https://<<sap_vm_provision_ibmcloud_powervs_region>>.power-iaas.cloud.ibm.com/
__sap_vm_provision_ibmcloud_powervs_location_to_powervs_region:
  dal10: "us-south"
  dal12: "us-south"
  us-south: "us-south"
  us-east: "us-east"
  wdc06: "us-east"
  wdc07: "us-east"
  sao01: "sao"
  sao02: "sao"
  tor01: "tor"
  eu-de-1: "eu-de"
  eu-de-2: "eu-de"
  lon04: "lon"
  lon06: "lon"
  mad02: "mad"
  mad04: "mad"
  syd04: "syd"
  syd05: "syd"
  tok04: "tok"
  osa21: "osa"
